#!/usr/bin/env python3
"""
Regenerate the LightAuth launcher icon.

The mark is a padlock drawn as line art — shackle arc, rounded body, keyhole — white
on black, matching the icon language of the sibling Light Phone III tools.

Geometry is defined once, in the 108x108 adaptive-icon canvas, and emitted twice: as
Android vector paths and as raster fallbacks. Everything sits inside the 18..90 safe
zone so no launcher mask can clip it.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)
STROKE = 5.0

# Body: rounded rectangle, centreline coordinates.
BODY = (31.0, 53.0, 77.0, 83.0)  # left, top, right, bottom
BODY_R = 6.0

# Shackle: upper half of a circle, sitting on the body's top edge.
SHACKLE_C = (54.0, 53.0)
SHACKLE_R = 15.0

# Keyhole: a filled dot with a short stem, the one solid in an otherwise hollow mark.
KEYHOLE_C = (54.0, 65.0)
KEYHOLE_R = 4.0
KEYHOLE_STEM = 76.0  # stem runs from the dot's centre down to here

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2
    left, top, right, bottom = BODY
    extents = [
        (left - edge, top - edge),
        (right + edge, bottom + edge),
        (SHACKLE_C[0] - SHACKLE_R - edge, SHACKLE_C[1] - SHACKLE_R - edge),
        (SHACKLE_C[0] + SHACKLE_R + edge, SHACKLE_C[1]),
        (KEYHOLE_C[0], KEYHOLE_STEM + edge),
    ]
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x}, {y}) escapes the safe zone"
    # The shackle must not poke out past the sides of the body.
    assert left < SHACKLE_C[0] - SHACKLE_R and SHACKLE_C[0] + SHACKLE_R < right


def body_path() -> str:
    left, top, right, bottom = BODY
    r = BODY_R
    return (
        f"M {left + r},{top} H {right - r} "
        f"A {r},{r} 0 0 1 {right},{top + r} V {bottom - r} "
        f"A {r},{r} 0 0 1 {right - r},{bottom} H {left + r} "
        f"A {r},{r} 0 0 1 {left},{bottom - r} V {top + r} "
        f"A {r},{r} 0 0 1 {left + r},{top} Z"
    )


def shackle_path() -> str:
    cx, cy = SHACKLE_C
    r = SHACKLE_R
    # Left foot, sweep clockwise over the top, right foot.
    return f"M {cx - r},{cy} A {r},{r} 0 0 1 {cx + r},{cy}"


def stem_path() -> str:
    cx, cy = KEYHOLE_C
    return f"M {cx},{cy} V {KEYHOLE_STEM}"


def dot_path() -> str:
    cx, cy = KEYHOLE_C
    r = KEYHOLE_R
    return (
        f"M {cx - r},{cy} A {r},{r} 0 1 0 {cx + r},{cy} "
        f"A {r},{r} 0 1 0 {cx - r},{cy} Z"
    )


def write_vectors() -> None:
    background = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's OLED these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h{CANVAS}v{CANVAS}h-{CANVAS}z" />
</vector>
"""

    def stroked(path: str) -> str:
        return f"""    <path
        android:pathData="{path}"
        android:fillColor="#00000000"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="{STROKE:g}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""

    def filled(path: str) -> str:
        return f"""    <path
        android:pathData="{path}"
        android:fillColor="#FFFFFF" />"""

    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate_icon.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
{stroked(shackle_path())}
{stroked(body_path())}
{filled(dot_path())}
{stroked(stem_path())}
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    s = SUPERSAMPLE
    white = (255, 255, 255, 255)
    img = Image.new("RGBA", (CANVAS * s, CANVAS * s), (0, 0, 0, 255))
    d = ImageDraw.Draw(img)
    w = int(STROKE * s)

    left, top, right, bottom = (v * s for v in BODY)
    d.rounded_rectangle([left, top, right, bottom], radius=BODY_R * s, outline=white, width=w)

    cx, cy = (v * s for v in SHACKLE_C)
    r = SHACKLE_R * s
    # PIL angles start at 3 o'clock and run clockwise on a y-down canvas, so the upper
    # half of the circle is 180 -> 360.
    d.arc([cx - r, cy - r, cx + r, cy + r], 180, 360, fill=white, width=w)
    for x in (cx - r, cx + r):  # round caps on the shackle feet
        d.ellipse([x - w / 2, cy - w / 2, x + w / 2, cy + w / 2], fill=white)

    kx, ky = (v * s for v in KEYHOLE_C)
    d.line([kx, ky, kx, KEYHOLE_STEM * s], fill=white, width=w)
    d.ellipse(
        [kx - w / 2, KEYHOLE_STEM * s - w / 2, kx + w / 2, KEYHOLE_STEM * s + w / 2],
        fill=white,
    )
    kr = KEYHOLE_R * s
    d.ellipse([kx - kr, ky - kr, kx + kr, ky + kr], fill=white)

    # Crop to the 72x72 the launcher actually shows, so the legacy raster matches what
    # the adaptive icon looks like under a mask.
    lo, hi = SAFE
    out = img.crop((lo * s, lo * s, hi * s, hi * s)).resize((px, px), Image.LANCZOS)

    if circular:
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        mask = mask.resize((px, px), Image.LANCZOS)
        base = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        base.paste(out, (0, 0), mask)
        out = base
    return out


def write_rasters() -> None:
    for dpi, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{dpi}")
        os.makedirs(folder, exist_ok=True)
        render(px, False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon regenerated in", os.path.normpath(RES))
